# Mod主仓库
# https://github.com/eigeen/more-auto-shoutouts
#
# Q&A文档
# https://git.eigeen.com/eigeen/more-auto-shoutouts-docs

# 全局触发器冷却时间
# 冷却时间内，同一个触发器的消息将会被忽略
# 默认1秒用于防抖
#
# 触发器支持单独设置冷却时间覆盖全局设置，具体查看触发器设置
trigger_cd = 1

# ========== 太刀白刃 ==========
[[trigger]]
# 当有多个事件时，事件调用模式
# sequential_all: 顺序执行全部
# sequential_one: 顺序执行下一个
# random: 随机选取执行
action_mode = "sequential_all"
# 触发冷却时间
# 该项设置后，会覆盖全局设置`trigger_cd`
cooldown = 1

    # 触发条件设置（有且仅有一个）
    [trigger.trigger_on.longsword_level_changed]
    new = 1
    old = 0

    # 触发检查条件设置
    # 多个条件同时满足才会执行
    # [[trigger.check]]
    # weapon_type.value = 3

    # 触发事件设置
    [[trigger.action]]
    cmd = "SendChatMessage"
    # 彩色文本为游戏内支持，彩色文本参考Q&A文档
    param = "白刃"

# ========== 太刀黄刃 ==========
[[trigger]]
action_mode = "sequential_all"

    [trigger.trigger_on.longsword_level_changed]
    new = 2
    old = 1

    [[trigger.action]]
    cmd = "SendChatMessage"
    param = "黄刃"


# ========== 太刀红刃 ==========
[[trigger]]
action_mode = "sequential_all"

    [trigger.trigger_on.longsword_level_changed]
    new = 3
    old = 2

    [[trigger.action]]
    cmd = "SendChatMessage"
    param = "红刃"


# ========== 太刀进入任务 ==========
[[trigger]]
action_mode = "sequential_all"

    [trigger.trigger_on.quest_state]
    value = 2

    [[trigger.check]]
    weapon_type.value = 3

    [[trigger.action]]
    cmd = "SendChatMessage"
    param = "太刀加入游戏"


# ========== 太刀登龙动作 ==========
[[trigger]]
action_mode = "random"

    [trigger.trigger_on.fsm]
    new = { target = 3, id = 87 }

    [[trigger.check]]
    weapon_type.value = 3

    [[trigger.action]]
    cmd = "SendChatMessage"
    param = "登龙随机1"
    [[trigger.action]]
    cmd = "SendChatMessage"
    param = "登龙随机2"
    [[trigger.action]]
    cmd = "SendChatMessage"
    param = "登龙随机3"


# ========== 太刀居合动作 ==========
[[trigger]]
action_mode = "random"

    [trigger.trigger_on.fsm]
    new = { target = 3, id = 102 }

    [[trigger.check]]
    weapon_type.value = 3

    [[trigger.action]]
    cmd = "SendChatMessage"
    param = "居合随机1"
    [[trigger.action]]
    cmd = "SendChatMessage"
    param = "居合随机2"


# ========== 虫棍进入任务 ==========
[[trigger]]
action_mode = "sequential_all"

    [trigger.trigger_on.quest_state]
    value = 2

    [[trigger.check]]
    weapon_type.value = 10

    [[trigger.action]]
    cmd = "SendChatMessage"
    param = "虫棍1"


# ========== 虫棍红灯 ==========
[[trigger]]
action_mode = "random"

    [trigger.trigger_on.insect_glaive_light]
    red = { new = { gt = 0 }, old = { le = 0 } }

    [[trigger.action]]
    cmd = "SendChatMessage"
    param = "红灯"


# ========== 虫棍白灯 ==========
[[trigger]]
action_mode = "random"

    [trigger.trigger_on.insect_glaive_light]
    white = { new = { gt = 0 }, old = { le = 0 } }

    [[trigger.action]]
    cmd = "SendChatMessage"
    param = "白灯"


# ========== 虫棍黄灯 ==========
[[trigger]]
action_mode = "random"

    [trigger.trigger_on.insect_glaive_light]
    yellow = { new = { gt = 0 }, old = { le = 0 } }

    [[trigger.action]]
    cmd = "SendChatMessage"
    param = "黄灯"


# ========== 虫棍三灯 ==========
[[trigger]]
action_mode = "random"

    [trigger.trigger_on.insect_glaive_light]
    red = { new = { gt = 0 } }
    white = { new = { gt = 0 } }
    yellow = { new = { gt = 0 } }

    [[trigger.action]]
    cmd = "SendChatMessage"
    param = "三灯"


# ========== 猎虫强化动作 ==========
[[trigger]]
action_mode = "random"

    [trigger.trigger_on.fsm]
    new = { target = 3, id = 133 }

    [[trigger.check]]
    weapon_type.value = 10

    [[trigger.action]]
    cmd = "SendChatMessage"
    param = "猎虫强化"


# ========== 盾斧瓶子充满 ==========
[[trigger]]
action_mode = "random"

    [trigger.trigger_on.charge_blade]
    phials = { new = "full" }

    [[trigger.action]]
    cmd = "SendChatMessage"
    param = "瓶子充满"


# ========== 盾斧超解动作 ==========
[[trigger]]
action_mode = "random"

    [trigger.trigger_on.fsm]
    new = { target = 3, id = 120 }

    [[trigger.check]]
    weapon_type.value = 9

    [[trigger.action]]
    cmd = "SendChatMessage"
    param = "超解"


# ========== 盾斧电锯启用 ==========
[[trigger]]
action_mode = "random"

    [trigger.trigger_on.charge_blade]
    power_axe_timer = { new = "enabled" }

    [[trigger.action]]
    cmd = "SendChatMessage"
    param = "开电锯"


# ========== 盾斧红盾启用 ==========
[[trigger]]
action_mode = "random"

    [trigger.trigger_on.charge_blade]
    shield_charge_timer = { new = { gt = 0 }, old = { le = 0 } }

    [[trigger.action]]
    cmd = "SendChatMessage"
    param = "开红盾"


# ========== 使用道具 ==========
[[trigger]]
action_mode = "sequential_all"

    [trigger.trigger_on.use_item]
    item_id = 23

    [[trigger.action]]
    cmd = "SendChatMessage"
    param = "使用了怪力药丸"


# ========== 使用衣装 ==========
[[trigger]]
action_mode = "sequential_all"

    [trigger.trigger_on.use_item]
    item_id = 131

    [[trigger.action]]
    cmd = "SendChatMessage"
    param = "使用了回避衣装"


# ========== 真蓄造成伤害 ==========
[[trigger]]
action_mode = "sequential_all"

    [trigger.trigger_on.damage]
    value = { gt = 200 }

    [[trigger.check]]
    weapon_type.value = 0

    [[trigger.check]]
    fsm.value = { target = 3, id = 137 }

    [[trigger.action]]
    cmd = "SendChatMessage"
    param = "强击真三蓄！造成了{{damage}}伤害"


# 开发中/计划开发

# [[trigger]]
# action_mode = "random"

# [[trigger.action]]
# cmd = "SEND_CHAT_MESSAGE"
# param = "裸指针操作"

# [[trigger.condition]]
# key = "rawptr"
# value = { base = 0x123, offsets = [0x1, 0x2, 0x3], type = "i32", value = 1}
